const ApiConstants = {
	AUTH: {
		BASE_URL: 'http://localhost:4000/admin',
		SIGNUP: '/sign-up',
		SIGN_IN: '/sign-in',
	},
	UTILS: {
		BASE_URL: 'http://localhost:4000/utils',
		UPLOAD_FILE: '/upload',
		ADD_CONTACT: '/contact',
	},
	PRODUCTS: {
		BASE_URL: 'http://localhost:4000/admin',
		GET_ALL_PRODUCTS: '/products',
		ADD_NEW_PRODUCT: '/product',
		GET_SINGLE: '/product',
		EDIT_PRODUCT: '/product',
		ARCHIVE_PRODUCT: '/product/archive',
	},
	AMAZON_PRODUCTS: {
		BASE_URL: 'http://localhost:4000/admin',
		GET_ALL_PRODUCTS: '/amazon-products',
		ADD_NEW_PRODUCT: '/amazon-product',
		GET_SINGLE: '/amazon-product',
		EDIT_PRODUCT: '/amazon-product',
		ARCHIVE_PRODUCT: '/amazon-product/archive',
	},
	BUNDLES: {
		BASE_URL: 'http://localhost:4000/bundles',
		GET_ALL_BUNDLES: '/',
		GET_SINGLE_BUNDLE: '/bundle',
	},
	USERS: {
		BASE_URL: 'http://localhost:4000/admin',
		ADD_NEW_USER_FROM_EXCEL: '/excel',
		GET_ALL: '/users',
		GET_SINGLE: '/user',
		EDIT_USER: '/user',
		DELETE_USER: '/user',
		ADD_NEW_USER: '/user',
	},
	USERS_FROM_EXCEL: {
		BASE_URL: 'http://localhost:4000/admin',
	},
	ADMIN: {
		BASE_URL: 'http://localhost:4000/admin',
		GET_MY_PROFILE: '/profile',
		EDIT_MY_PROFILE: '/profile',
		GET_ALL_ADMINS: '/',
		ADD_NEW_ADMIN: '/',
		GET_SINGLE_ADMIN: '/admin',
		EDIT_ADMIN: '/admin',
		DELETE_ADMIN: '/admin',
		GET_STATISTICS: '/statistics',
		GET_ALL_INFLUENCERS: '/influencers',
		GET_INFLUENCER_BY_ID: '/influencer',
		ADD_INFLUENCER: '/influencer',
		DELETE_INFLUENCER: '/influencer',
		UPDATE_INFLUENCER: '/influencer',
		ADD_STORE: '/store',
		EDIT_STORE: '/store',
		DELETE_STORE: '/store',
	},
}
export default ApiConstants
